/**
 * generated by Xtext 2.25.0
 */
package org.ppgti.mydsl.myDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.ppgti.mydsl.myDSL.MyDSLFactory
 * @model kind="package"
 * @generated
 */
public interface MyDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ppgti.org/mydsl/MyDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDSLPackage eINSTANCE = org.ppgti.mydsl.myDSL.impl.MyDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link org.ppgti.mydsl.myDSL.impl.PessoasImpl <em>Pessoas</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.ppgti.mydsl.myDSL.impl.PessoasImpl
   * @see org.ppgti.mydsl.myDSL.impl.MyDSLPackageImpl#getPessoas()
   * @generated
   */
  int PESSOAS = 0;

  /**
   * The feature id for the '<em><b>Base Dados</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PESSOAS__BASE_DADOS = 0;

  /**
   * The number of structural features of the '<em>Pessoas</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PESSOAS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.ppgti.mydsl.myDSL.impl.PessoaImpl <em>Pessoa</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.ppgti.mydsl.myDSL.impl.PessoaImpl
   * @see org.ppgti.mydsl.myDSL.impl.MyDSLPackageImpl#getPessoa()
   * @generated
   */
  int PESSOA = 1;

  /**
   * The feature id for the '<em><b>Nome</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PESSOA__NOME = 0;

  /**
   * The feature id for the '<em><b>Sobrenome</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PESSOA__SOBRENOME = 1;

  /**
   * The number of structural features of the '<em>Pessoa</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PESSOA_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.ppgti.mydsl.myDSL.Pessoas <em>Pessoas</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pessoas</em>'.
   * @see org.ppgti.mydsl.myDSL.Pessoas
   * @generated
   */
  EClass getPessoas();

  /**
   * Returns the meta object for the containment reference list '{@link org.ppgti.mydsl.myDSL.Pessoas#getBaseDados <em>Base Dados</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Base Dados</em>'.
   * @see org.ppgti.mydsl.myDSL.Pessoas#getBaseDados()
   * @see #getPessoas()
   * @generated
   */
  EReference getPessoas_BaseDados();

  /**
   * Returns the meta object for class '{@link org.ppgti.mydsl.myDSL.Pessoa <em>Pessoa</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pessoa</em>'.
   * @see org.ppgti.mydsl.myDSL.Pessoa
   * @generated
   */
  EClass getPessoa();

  /**
   * Returns the meta object for the attribute '{@link org.ppgti.mydsl.myDSL.Pessoa#getNome <em>Nome</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nome</em>'.
   * @see org.ppgti.mydsl.myDSL.Pessoa#getNome()
   * @see #getPessoa()
   * @generated
   */
  EAttribute getPessoa_Nome();

  /**
   * Returns the meta object for the attribute '{@link org.ppgti.mydsl.myDSL.Pessoa#getSobrenome <em>Sobrenome</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sobrenome</em>'.
   * @see org.ppgti.mydsl.myDSL.Pessoa#getSobrenome()
   * @see #getPessoa()
   * @generated
   */
  EAttribute getPessoa_Sobrenome();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDSLFactory getMyDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.ppgti.mydsl.myDSL.impl.PessoasImpl <em>Pessoas</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.ppgti.mydsl.myDSL.impl.PessoasImpl
     * @see org.ppgti.mydsl.myDSL.impl.MyDSLPackageImpl#getPessoas()
     * @generated
     */
    EClass PESSOAS = eINSTANCE.getPessoas();

    /**
     * The meta object literal for the '<em><b>Base Dados</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PESSOAS__BASE_DADOS = eINSTANCE.getPessoas_BaseDados();

    /**
     * The meta object literal for the '{@link org.ppgti.mydsl.myDSL.impl.PessoaImpl <em>Pessoa</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.ppgti.mydsl.myDSL.impl.PessoaImpl
     * @see org.ppgti.mydsl.myDSL.impl.MyDSLPackageImpl#getPessoa()
     * @generated
     */
    EClass PESSOA = eINSTANCE.getPessoa();

    /**
     * The meta object literal for the '<em><b>Nome</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PESSOA__NOME = eINSTANCE.getPessoa_Nome();

    /**
     * The meta object literal for the '<em><b>Sobrenome</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PESSOA__SOBRENOME = eINSTANCE.getPessoa_Sobrenome();

  }

} //MyDSLPackage
