/**
 * generated by Xtext 2.25.0
 */
package org.ppgti.mydsl.myDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pessoa</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.ppgti.mydsl.myDSL.Pessoa#getNome <em>Nome</em>}</li>
 *   <li>{@link org.ppgti.mydsl.myDSL.Pessoa#getSobrenome <em>Sobrenome</em>}</li>
 * </ul>
 *
 * @see org.ppgti.mydsl.myDSL.MyDSLPackage#getPessoa()
 * @model
 * @generated
 */
public interface Pessoa extends EObject
{
  /**
   * Returns the value of the '<em><b>Nome</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nome</em>' attribute.
   * @see #setNome(String)
   * @see org.ppgti.mydsl.myDSL.MyDSLPackage#getPessoa_Nome()
   * @model
   * @generated
   */
  String getNome();

  /**
   * Sets the value of the '{@link org.ppgti.mydsl.myDSL.Pessoa#getNome <em>Nome</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nome</em>' attribute.
   * @see #getNome()
   * @generated
   */
  void setNome(String value);

  /**
   * Returns the value of the '<em><b>Sobrenome</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sobrenome</em>' attribute.
   * @see #setSobrenome(String)
   * @see org.ppgti.mydsl.myDSL.MyDSLPackage#getPessoa_Sobrenome()
   * @model
   * @generated
   */
  String getSobrenome();

  /**
   * Sets the value of the '{@link org.ppgti.mydsl.myDSL.Pessoa#getSobrenome <em>Sobrenome</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sobrenome</em>' attribute.
   * @see #getSobrenome()
   * @generated
   */
  void setSobrenome(String value);

} // Pessoa
