/**
 * generated by Xtext 2.25.0
 */
package org.ppgti.mydsl.myDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pessoas</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.ppgti.mydsl.myDSL.Pessoas#getBaseDados <em>Base Dados</em>}</li>
 * </ul>
 *
 * @see org.ppgti.mydsl.myDSL.MyDSLPackage#getPessoas()
 * @model
 * @generated
 */
public interface Pessoas extends EObject
{
  /**
   * Returns the value of the '<em><b>Base Dados</b></em>' containment reference list.
   * The list contents are of type {@link org.ppgti.mydsl.myDSL.Pessoa}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Base Dados</em>' containment reference list.
   * @see org.ppgti.mydsl.myDSL.MyDSLPackage#getPessoas_BaseDados()
   * @model containment="true"
   * @generated
   */
  EList<Pessoa> getBaseDados();

} // Pessoas
