/**
 * generated by Xtext 2.25.0
 */
package org.ppgti.mydsl.myDSL.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.ppgti.mydsl.myDSL.MyDSLFactory;
import org.ppgti.mydsl.myDSL.MyDSLPackage;
import org.ppgti.mydsl.myDSL.Pessoa;
import org.ppgti.mydsl.myDSL.Pessoas;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class MyDSLPackageImpl extends EPackageImpl implements MyDSLPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass pessoasEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass pessoaEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.ppgti.mydsl.myDSL.MyDSLPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private MyDSLPackageImpl()
  {
    super(eNS_URI, MyDSLFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link MyDSLPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static MyDSLPackage init()
  {
    if (isInited) return (MyDSLPackage)EPackage.Registry.INSTANCE.getEPackage(MyDSLPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredMyDSLPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    MyDSLPackageImpl theMyDSLPackage = registeredMyDSLPackage instanceof MyDSLPackageImpl ? (MyDSLPackageImpl)registeredMyDSLPackage : new MyDSLPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theMyDSLPackage.createPackageContents();

    // Initialize created meta-data
    theMyDSLPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theMyDSLPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(MyDSLPackage.eNS_URI, theMyDSLPackage);
    return theMyDSLPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPessoas()
  {
    return pessoasEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPessoas_BaseDados()
  {
    return (EReference)pessoasEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPessoa()
  {
    return pessoaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPessoa_Nome()
  {
    return (EAttribute)pessoaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPessoa_Sobrenome()
  {
    return (EAttribute)pessoaEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MyDSLFactory getMyDSLFactory()
  {
    return (MyDSLFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    pessoasEClass = createEClass(PESSOAS);
    createEReference(pessoasEClass, PESSOAS__BASE_DADOS);

    pessoaEClass = createEClass(PESSOA);
    createEAttribute(pessoaEClass, PESSOA__NOME);
    createEAttribute(pessoaEClass, PESSOA__SOBRENOME);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes

    // Initialize classes and features; add operations and parameters
    initEClass(pessoasEClass, Pessoas.class, "Pessoas", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPessoas_BaseDados(), this.getPessoa(), null, "baseDados", null, 0, -1, Pessoas.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(pessoaEClass, Pessoa.class, "Pessoa", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPessoa_Nome(), ecorePackage.getEString(), "nome", null, 0, 1, Pessoa.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPessoa_Sobrenome(), ecorePackage.getEString(), "sobrenome", null, 0, 1, Pessoa.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //MyDSLPackageImpl
