/**
 * generated by Xtext 2.25.0
 */
package org.ppgti.mydsl.myDSL.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.ppgti.mydsl.myDSL.MyDSLPackage;
import org.ppgti.mydsl.myDSL.Pessoa;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Pessoa</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.ppgti.mydsl.myDSL.impl.PessoaImpl#getNome <em>Nome</em>}</li>
 *   <li>{@link org.ppgti.mydsl.myDSL.impl.PessoaImpl#getSobrenome <em>Sobrenome</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PessoaImpl extends MinimalEObjectImpl.Container implements Pessoa
{
  /**
   * The default value of the '{@link #getNome() <em>Nome</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNome()
   * @generated
   * @ordered
   */
  protected static final String NOME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNome() <em>Nome</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNome()
   * @generated
   * @ordered
   */
  protected String nome = NOME_EDEFAULT;

  /**
   * The default value of the '{@link #getSobrenome() <em>Sobrenome</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSobrenome()
   * @generated
   * @ordered
   */
  protected static final String SOBRENOME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSobrenome() <em>Sobrenome</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSobrenome()
   * @generated
   * @ordered
   */
  protected String sobrenome = SOBRENOME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PessoaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDSLPackage.Literals.PESSOA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNome()
  {
    return nome;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNome(String newNome)
  {
    String oldNome = nome;
    nome = newNome;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDSLPackage.PESSOA__NOME, oldNome, nome));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSobrenome()
  {
    return sobrenome;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSobrenome(String newSobrenome)
  {
    String oldSobrenome = sobrenome;
    sobrenome = newSobrenome;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDSLPackage.PESSOA__SOBRENOME, oldSobrenome, sobrenome));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDSLPackage.PESSOA__NOME:
        return getNome();
      case MyDSLPackage.PESSOA__SOBRENOME:
        return getSobrenome();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDSLPackage.PESSOA__NOME:
        setNome((String)newValue);
        return;
      case MyDSLPackage.PESSOA__SOBRENOME:
        setSobrenome((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDSLPackage.PESSOA__NOME:
        setNome(NOME_EDEFAULT);
        return;
      case MyDSLPackage.PESSOA__SOBRENOME:
        setSobrenome(SOBRENOME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDSLPackage.PESSOA__NOME:
        return NOME_EDEFAULT == null ? nome != null : !NOME_EDEFAULT.equals(nome);
      case MyDSLPackage.PESSOA__SOBRENOME:
        return SOBRENOME_EDEFAULT == null ? sobrenome != null : !SOBRENOME_EDEFAULT.equals(sobrenome);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (nome: ");
    result.append(nome);
    result.append(", sobrenome: ");
    result.append(sobrenome);
    result.append(')');
    return result.toString();
  }

} //PessoaImpl
