/*
 * generated by Xtext 2.25.0
 */
package org.ppgti.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.ppgti.mydsl.ui.internal.MydslActivator;

public class MyDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MydslActivator.getInstance().getInjector("org.ppgti.mydsl.MyDSL");
	}

}
