/*
 * generated by Xtext 2.25.0
 */
package org.ppgti.mydsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyDSLScopeProvider extends DelegatingScopeProvider {
}
