/*
 * generated by Xtext 2.25.0
 */
package org.ppgti.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MyDSLUiModule extends AbstractMyDSLUiModule {

	public MyDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
