/*
 * generated by Xtext 2.25.0
 */
package org.ppgti.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.ppgti.mydsl.MyDSLRuntimeModule;
import org.ppgti.mydsl.MyDSLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MyDSLIdeSetup extends MyDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MyDSLRuntimeModule(), new MyDSLIdeModule()));
	}
	
}
