/*
 * generated by Xtext 2.25.0
 */
package org.ppgti.mydsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MyDSLStandaloneSetup extends MyDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new MyDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
